### PR TITLE
Throw exception on failure status codes

### LINKED ISSUE #4: Loading dialog not properly handling server-side errors
A lesson has a configuration problem but the loading dialog didn't update to notify the user

It does look like the web-side timeout does notify the user, however. "Error while waiting for lesson to initialize: undefined"

This also happens for undefined lesson IDs. When I request a lesson ID that doesn't exist, it keeps acting like it has a handle on a new livelesson:

From syringe logs:

```
10.32.0.4 - - [21/Jan/2020:20:01:39 +0000] "GET /exp/lesson/17 HTTP/1.1" 500 68
10.32.0.4 - - [21/Jan/2020:20:01:39 +0000] "POST /exp/livelesson HTTP/1.1" 500 104
10.32.0.4 - - [21/Jan/2020:20:01:40 +0000] "GET /exp/livelesson/undefined HTTP/1.1" 500 74
...
```

So we need to handle unexpected error codes and error values in the reponse payloads.

### PR DESCRIPTION
**Pull request by Mierdin**
In #4, it was discovered that a variety of errors weren't being handled properly. Not only were these errors not being bubbled up to the user in the progress modal, it seemed like they weren't even impacting application flow - an error response in the initial livelesson request, for instance, wouldn't prevent the rest of the front-end code from executing, and trying to get a livelesson by an `undefined` UUID.

Turns out that the javascript `fetch()` function, used by both `use-fetch.js` and `use-polling-request.js`, doesn't actually throw an exception for responses with error codes. So, the existing exception handling never triggers. I'm not sure if I ever knew this, but I do now :smile:

This PR adds logic to throw an exception when a status code of 400 or above is detected, in both of these functions. It also fixes a bug where the wrong variable was being sent to the error message l8n strings. Combined, these changes allow errors to not only properly halt the workflow of retrieving a lesson from the back-end, it also provides the right message to the user.

Closes #4

### CODE REVIEW

**Comment by nlundquist** [comment]
These changes look perfect 👍 Nice catch.

Somehow I spaced on the fact that a complete response with a non-2xx code wouldn't throw and could hypothetically return a body, so the attempt to read the body wouldn't error either.

**Review by nlundquist — APPROVED** [review]

**Comment by Mierdin** [comment]
Thanks for the review - and no worries, it wasn't obvious to me at all that it wouldn't throw an exception. I spent a few hours adding debugs under the false assumption that - surely - an exception was being thrown for 500 error codes. But I guess in retrospect this kind of makes sense - it gives greater control over how you respond to errors, you may want to throw an exception, like we do here, but you may not.

Oh well, will file this away in my "lessons learned" bucket. Thanks for the follow-up!

File: helpers/use-fetch.js [hunk 1]
```diff
@@ -26,8 +26,13 @@ export default function useFetch(path, options) {
 
       try {
         const response = await fetch(url, options);
+        const data = options && options.text ? await response.text() : await response.json();
```
Comment (nlundquist) [inline helpers/use-fetch.js:29]: you may want to move this to after the `response.status` check. that way `response.text()` or `response.json()` won't potentially error and throw before the status check

File: helpers/use-polling-request.js [hunk 2]
```diff
@@ -63,7 +63,10 @@ export default function usePollingRequest({
         try {
           const response = await fetch(`${progressRequestURL}`);
           const data = await response.json();
```
Comment (nlundquist) [inline helpers/use-polling-request.js]: you may want to move this to after the `response.status` check. that way `response.text()` or `response.json()` won't potentially error and throw before the status check

Comment (nlundquist) [inline helpers/use-polling-request.js:65]: you may want to move this to after the `response.status` check. that way `response.json()` won't potentially error and throw before the status check
